
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 31;
  public static final int parentesisaper = 26;
  public static final int ampersand = 24;
  public static final int coma = 19;
  public static final int igual = 32;
  public static final int barraor = 39;
  public static final int identificador = 2;
  public static final int letra = 43;
  public static final int guion = 14;
  public static final int numeral = 22;
  public static final int cadenavar = 9;
  public static final int comillasimple = 25;
  public static final int menor = 16;
  public static final int porcentaje = 29;
  public static final int EOF = 0;
  public static final int mas = 28;
  public static final int comilladoble = 20;
  public static final int error = 1;
  public static final int mayor = 15;
  public static final int entero = 3;
  public static final int punto = 42;
  public static final int dospuntos = 13;
  public static final int parentesiscierre = 27;
  public static final int llaveaper = 40;
  public static final int acento = 38;
  public static final int potencia = 37;
  public static final int exclamacion = 21;
  public static final int guionbajo = 18;
  public static final int llavecierre = 41;
  public static final int nombreexpresion = 10;
  public static final int conj = 11;
  public static final int cadenamayus = 8;
  public static final int arroba = 34;
  public static final int cadenanum = 6;
  public static final int puntocoma = 17;
  public static final int cadenamin = 7;
  public static final int dolar = 23;
  public static final int trazo = 12;
  public static final int asterisco = 30;
  public static final int especialc = 5;
  public static final int interrogacion = 33;
  public static final int corchetecierre = 36;
  public static final int corcheteaper = 35;
  public static final int cadena = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identificador",
  "entero",
  "cadena",
  "especialc",
  "cadenanum",
  "cadenamin",
  "cadenamayus",
  "cadenavar",
  "nombreexpresion",
  "conj",
  "trazo",
  "dospuntos",
  "guion",
  "mayor",
  "menor",
  "puntocoma",
  "guionbajo",
  "coma",
  "comilladoble",
  "exclamacion",
  "numeral",
  "dolar",
  "ampersand",
  "comillasimple",
  "parentesisaper",
  "parentesiscierre",
  "mas",
  "porcentaje",
  "asterisco",
  "slash",
  "igual",
  "interrogacion",
  "arroba",
  "corcheteaper",
  "corchetecierre",
  "potencia",
  "acento",
  "barraor",
  "llaveaper",
  "llavecierre",
  "punto",
  "letra"
  };
}

